-- questions: pool of voice-intro questions per community.
-- Generated by LLM from the admin's setup interview, then admin-reviewed.

create type public.question_source as enum ('admin_approved', 'admin_added');

create table public.questions (
  id uuid primary key default gen_random_uuid(),
  community_id uuid not null references public.communities(id) on delete cascade,
  question_text text not null,
  source public.question_source not null,
  created_at timestamptz not null default now(),
  constraint question_text_length check (char_length(question_text) between 5 and 500)
);

create index idx_questions_community on public.questions(community_id);

alter table public.questions enable row level security;

create policy "questions_admin_all" on public.questions
  for all using (
    exists (
      select 1 from public.communities c
      where c.id = questions.community_id and c.owner_admin_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from public.communities c
      where c.id = questions.community_id and c.owner_admin_id = auth.uid()
    )
  );
